kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster
featureGates:
  APIServerTracing: true
  KubeletTracing: true
nodes:
- role: control-plane
  image: localhost:5001/custom:kubelet
  extraMounts:
  - hostPath: /home/vrutkovs/src/github.com/vrutkovs/kind-tracing/kubeapi
    containerPath: /etc/kubernetes/apiserver
    readOnly: true
    selinuxRelabel: false
  - hostPath: /home/vrutkovs/src/github.com/vrutkovs/kind-tracing/kubeadm-patches
    containerPath: /etc/kubernetes/patches
    readOnly: true
    selinuxRelabel: false
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        container-runtime-endpoint: "unix:///var/run/crio/crio.sock"
    patches:
      directory: /etc/kubernetes/patches
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        tracing-config-file: /etc/kubernetes/apiserver/trace.yaml
      extraVolumes:
        - name: apitracing
          hostPath: /etc/kubernetes/apiserver/trace.yaml
          mountPath: /etc/kubernetes/apiserver/trace.yaml
          readOnly: true
          pathType: "File"
  - |
    kind: KubeletConfiguration
    cgroupDriver: "cgroupfs"
    tracing:
      endpoint: "127.0.0.1:4317"
      samplingRatePerMillion: 999999
